image: docker:latest
services:
  - docker:dind

stages:
  - build-frontend
  - build-artefact
  - build-container
  - deploy-sandbox

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  REGISTRY_IMAGE: ebispot/ontotools-curation-service
  SERVICE_NAME: ontotools-curation-service

build-front:
  image: node:10.15.3
  stage: build-frontend
  script:
    - npm -v
    - node -v
    - cd frontend
    - rm -rf node_modules
    - npm install
    - CI=false npm run build:sandbox
  artifacts:
    paths:
      - frontend/build/*

build-war:
  image: maven:3-jdk-12
  stage: build-artefact
  script:
    - mkdir src/main/webapp
    - mv frontend/build/* src/main/webapp/
    - ls -lah src/main/webapp
    - mvn clean package spring-boot:repackage -DskipTests=true
  dependencies:
    - build-front
  artifacts:
    paths:
      - target/*.war
  only:
    - release-test

build-container:
  stage: build-container
  script:
    - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
    - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
    - docker build --cache-from $REGISTRY_IMAGE:latest -t $REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy-sandbox:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-sandbox
  script:
  - echo "Deploy to sandbox server"
  - mkdir -p /root/.kube
  - echo ${SANBOX_KUBECONF} | base64 -d > /root/.kube/config
  - helm init --stable-repo-url https://charts.helm.sh/stable
  - helm delete --purge ontotools-curation-service || true
  - helm install --name ontotools-curation-service --set k8Namespace=ontotools,image.repository=$REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.secretsName=ontotools-secrets,image.env.secretsKey=db-pwd ./k8chart/ --wait
  environment:
    name: sandbox
  when: manual
  only:
  - release-test
